### ISSUE TITLE
Plan for project

### ISSUE THREAD

**Issue by pmh-only** [GBSWHS/gbsw.hs.kr-gitops#1]
## concepts
* github를 통해 gbsw.hs.kr 도메인을 관리
* 레포 루트에 yml 파일을 생성해 Cloudflare API로 동기화
* README.md에 도메인들 HealthCheck 상황 표시
* Issue로 도메인 추가/변경/삭제 요청 가능하도록 하고
* 실제 파일 변경은 Pull Request로 진행 (혹은 직접 PR 날려도 되고)

## why?
* Cloudflare 계정에 들어가서 편집하는것도 불편하고
* 학교 도메인 Cloudflare 계정이 있는지 많이 잘 모르는거 같아서
* Github 통해서 Gitops로 관리하면 새로운 도메인이 등록되면 다른 사람이 알람 받기도 편하고
* 도메인 중복도 방지할 수 있고 한번 이슈에서 거를수도 있고
* 유지보수나 인수인계나 측면에서 쉬울꺼 같아서

## why not Terraform
* 신입생들 잘 모르잖아

## todo
- [x] #1 (Concept 작성)
- [x] 기존에 있던 레코드들 여기 레포로 마이그레이션
- [x] yml을 읽어 동기화 하는 스크립트 작성
- [x] Github Actions 통해 push 발생하면 cloudflare api와 동기화
- [ ] Github Actions 통해 주기적으로 Health Check후 README 에 기재

### A record
```yml
record-type: A
comment: Example Site
name: example.gbsw.hs.kr
ip: 123.234.123.234
cloudflare: true # Cloudflare를 통한 DDoS 방어 / HTTPS 지원 (대신 포트가 80/443으로 제한)
```

### CNAME record
```yml
record-type: CNAME
comment: Example Site
name: example.gbsw.hs.kr
target: d1i9bw1f.cloudfront.com
cloudflare: true
```

### TXT record
```yml
record-type: TXT
comment: Some Value
name: hello.gbsw.hs.kr
content: HELLO_WORLD
```

### NS record
```yml
record-type: NS
comment: Some Nameserver
name: pmh.gbsw.hs.kr
nameserver: ns-773.awsdns-32.net
```

**Comment by pmh-only** [comment]
Cloudflare 레코드들 이 레포지트리로 마이그레이션 완료

**Comment by pmh-only** [comment]
yml을 읽어 동기화 하는 스크립트 작성 완료

**Comment by pmh-only** [comment]
Github Actions 통해 push 발생하면 cloudflare api와 동기화 완료
